### ISSUE TITLE
Add JS contract interaction to the project

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#17]
This project will include additional files that are canonical for Javascript projects to access deployed Aion contracts.

Blockers

- [ ] Aion web3 ABI bindings

Reference

https://github.com/jennijuju/Aion-ATS-Token-Contract-Java/tree/master/ContractInteraction

**Comment by fulldecent** [comment]
Requesting assistance and guidance from @jennjiuju

**Comment by jennijuju** [comment]
aion-web3 with ABI binding is released. 
 `npm`: npm install aion-web3@1.2.6-beta.1
github:  https://github.com/aionnetwork/aion_web3/tree/avm-support-update-2

`contract tx` example: https://github.com/jennijuju/web3_avm/blob/master/sendTransaction-withABI.js
`contract call` example: https://github.com/jennijuju/web3_avm/blob/master/contractCall-withABI.js

**Comment by fulldecent** [comment]
Thank you. aion-web3 is released. Now it is not necessary to include JS code inside this repo. Consistent with aip-041.
