### ISSUE TITLE
Use BigInteger for interacting with AVM

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#19]
Instead of `byte[]`

**Comment by fulldecent** [comment]
Implemented in b2ae784f0104c43b76d6a8c8c760286cca67312f

Requesting help from @jennijuju @jeff-aion

**Comment by jennijuju** [comment]
If you are using mvn aion4j, you will have to use `0.7.1-SNAPSHOT` to compile the contract with ABI version 1.

**Comment by jennijuju** [comment]
#22

**Comment by fulldecent** [comment]
Thank you. 8d9fdcd3aff1660406032ae9cc92baed31acb1ec
