### ISSUE TITLE
Updates notes when update AVM user lib is released

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#26]
Currently there is a warning in the README and AIP that we are using the pre-release user lib.

We that user lib should make a production release before we make a production release of the NFToken contract.

Work plan

- [x] Update build here since new vendor version is released
- [x] Update references if necessary
- [x] Update documentation

**Comment by jennijuju** [comment]
`0.7.2` is an official release. 
Furthur releases should be back-compatible with this version.

You can have a link to [aion4j maven cli github](https://github.com/bloxbean/aion4j-maven-plugin) for your users to refer for the latest version.

and you can refer to [this](https://docs.aion.network/docs/tools-maven-cli-update-maven) for updating the libs.

**Comment by fulldecent** [comment]
Thank you. Documentation added. Dependency updated.
