### ISSUE TITLE
Confirm if choices of Boolean vs. boolean in code are correct

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#29]

**Comment by fulldecent** [comment]
Requesting assistance @Jeff-aion

**Comment by jeff-aion** [comment]
`boolean` is a primitive type and `Boolean` is an object wrapper it is put inside when it needs to be passed through an object.  Wherever possible, the primitive `boolean` should be used (and `Boolean` is not supported in the ABI).  Confusion can arise given that the compiler will often auto-box and auto-unbox the primitive types into and out of their object wrappers.

Can you point me to a specific example so I can make sure that the boxing might not be doing some odd (probably just wasting energy)?

**Comment by fulldecent** [comment]
Ah, I see authoritative documentation is at https://docs.aion.network/docs/abi

The only place we are touching the ABI with boolean is here:

https://github.com/fulldecent/aion-aip040/blob/master/src/main/java/org/aion/NFToken.java#L115

**Comment by fulldecent** [comment]
Thank you. Yes that addresses it
