### ISSUE TITLE
Add 100% test coverage

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#7]
:x: CANT DO Add a test tool to CI to confirm 100% test coverage. 

---

All test cases use `MainEncoder`, `AIP040Encoder` and `NFTokenMockEncoder` to send message to the deployed contract.

:ng: = expect revert

- `MainEncoder`
  - [ ] Deploy using good arguments
  - [ ] :ng: Deploy using wrong argument count
  - [ ] :ng: Deploy using correct argument count but with a null value
- `NFTokenMockEncoder`
  - [ ] Mint to self, confirm total supply == self balance == 1
  - [ ] :ng: Mint to null
  - [ ] Mint to contract
  - [ ] Mint with tokenid = 0
  - [ ] Mint with 0 < tokenid < 2^256
  - [ ] :ng: Mint with tokenid < 0
  - [ ] :ng: Mint with tokenid >= 2^256
- `AIP040Encoder`
  - `aip040Name()`
    - [ ] Works with emoji
  - `aip040Symbol()`
    - [ ] Works with emoji
  - `aip040TotalSupply()`
    - [ ] Returns zero initially
    - [ ] Returns one after mint one
    - [ ] Returns 10 after batch mint 10
  - `aip040TokenOwner(BigInteger tokenId)`
    - [ ] :ng: With null token
    - [ ] Returns null for non existant token 999
    - [ ] Returns self after mint a token to self
  - `aip040TokenConsignee(BigInteger tokenId)`
    - [ ] 🆖 With null token
    - [ ] Returns null for non existant token 999
    - [ ] Returns otheraccount after consign a token to them
  - `aip040TokenUri(BigInteger tokenId)`
    - [ ] 🆖 With null token
    - [ ] Returns null for non existant token 999
    - [ ] Returns a url for existing token
  - `aip040OwnerBalance(Address owner)`
    - [ ] 🆖 With null address
    - [ ] Returns 0 for self initially
    - [ ] Returns 1 for self after mint
  - `aip040OwnerDoesAuthorize(Address owner, Address authorizee)`
    - [ ] 🆖 With null owner
    - [ ] :ng: with null authorizee
    - [ ] Returns false for self and other account initially
    - [ ] Returns true for self and other account after authorize
  - `aip040TokenAtIndex(BigInteger index)`
    - [ ] :ng: For index 0 initially
    - [ ] The token for index 0 after mint one token is that token
    - [ ] Mint 5 tokens, confirm set of those 5 tokens matches the tokenatindex(0...4)
    - [ ] Mint 5 tokens, transfer 2 to somebody else, confirm set of those 5 tokens matches the tokenatindex(0...4)
  - `aip040TokenForOwnerAtIndex(Address owner, BigInteger index)`
    - [ ] 🆖 For index 0 initially
    - [ ] The token for index 0 after mint to self is that token
    - [ ] Mint 5 tokens, confirm set of those 5 tokens matches the tokenatindex(0...4)
    - [ ] Mint 5 tokens, transfer last 2 to somebody else, confirm set of those remaining 3 tokens matches the tokenatindex(0...2)
  - `aip040TakeOwnership(Address currentOwner, BigInteger[] tokenIds)`
    - [ ] :ng: owner is null
    - [ ] :ng: consignee is null
    - [ ] :ng: tokenids is null
    - [ ] tokenids is empty
    - [ ] Mint a token to self, take from self
    - [ ] :ng: mint to self, take that token but list owner as other
    - [ ] :ng: mint to other, take from other
    - [ ] mint to other, other consigns you, take from them, confirm consignee is null, confirm you are new owner
    - [ ] 🆖 mint to other, other consigns you, take but list owner as bob
    - [ ] mint to other, other authorizes you, take from them, confirm you are new owner
    - [ ] :ng: mint to other, other authorizes you, take but list owner as bob
    - [ ] mint to other, other authorizes bob, bob consigns you, take from other
    - [ ] :ng: mint to other, other authorizes bob, bob consigns you, take but list owner as bob
    - [ ] :ng: mint to other, other authorizes you, other deauthorizes you, take from other
  - `aip040Consign(Address owner, Address consignee, BigInteger[] tokenIds)`
    - [ ] :ng: owner is null
    - [ ] :ng: consignee is null
    - [ ] :ng: tokenids is null
    - [ ] tokenids is empty
    - [ ] mint to self, consign to other, confirm other is consignee of token
    - [ ] mint to self, consign to other, other takes token, consignee is null
    - [ ] :ng: mint to self, consign to other but list owner as bob
    - [ ] mint two to self, consign both to other, confirm both are consigned to other
  - `aip040Authorize(Address authorizee)`
    - [ ] :ng: authorizee is null
    - [ ] authorize other, confirm other authorized
  - `aip040Deauthorize(Address priorAuthorizee)`
    - [ ] :ng: priorauthorizee is null
    - [ ] deauthorize other, confirm not authorized
    - [ ] authorized other, deauthorize other, confirm not authorized

- Events
  - `AIP040Transferred(Address priorOwner, Address newOwner, BigInteger tokenId)`
    - [ ] Mint token, confirm emit transferred
    - [ ] Mint token to self, take to self, confirm emitted
    - [ ] Mint to other, take to self, confirm emitted
    - [ ] Mint 2 to other, take both to self at same time, confirm emit two events
  - `AIP040Consigned(Address owner, Address consignee, BigInteger tokenId)`
    - [ ] mint to self, consign to other, confirm emitted
    - [ ] mint to other, authorize to self, consign to bob, confirm emitted
    - [ ] mint two to self, consign both to other at same time, confirm emitted
  - `AIP040Authorized(Address account, Address authorizee)`
    - [ ] authorize other, confirm emitted
    - [ ] authorize self, confirm emitted
  - `AIP040Deauthorized(Address account, Address priorAuthorizee)`
    - [ ] deauthorize other, confirm emitted
    - [ ] authorize other, deauthorize other, confirm emitted
    - [ ] authorize self, deauthorize self, confirm emitted

**Comment by fulldecent** [comment]
Requesting help: @jennjiuju

**Comment by jennijuju** [comment]
Done with travis CI.

**Comment by fulldecent** [comment]
Change coming. Tokens will be restricted to range 0...2^256-1

**Comment by fulldecent** [comment]
Added test for min and max token values at 53b77b9. Everything else done by @jennijuju, thank you!
